### ISSUE TITLE
Please ask if you have any dissertation references for these projects

### ISSUE THREAD

**Issue by hanrui234** [SokratG/Surround-View#10]
Please ask if you have any dissertation references for these projects

**Comment by SokratG** [comment]
> Please ask if you have any dissertation references for these projects

Hi @hanrui234,
I added paper information in README and [link to paper](https://link.springer.com/chapter/10.1007/978-3-031-11058-0_9)!

**Comment by hanrui234** [comment]
Thanks for your answer, really appreciate it
