### ISSUE TITLE
Can I run it without GPU?

### ISSUE THREAD

**Issue by CPFelix** [SokratG/Surround-View#14]
@SokratG My computer has no nvidia GPU,so I want to run your code with intel CPU,can it?

**Comment by SokratG** [comment]
@CPFelix Hi! Unfortunately you can't run the project without Nvidia GPU

**Comment by CPFelix** [comment]
@SokratG Thank for reply.There is also a question, is there any reference between this project and libxcam? I recently looked at the library of libcam, is there any comparison in effect?

**Comment by SokratG** [comment]
@CPFelix No, I didn't compare with libxcam. The libxcam doesn't support CUDA, but it support other GPU API like OpenCL, OpenGL, etc. I have not been able to run libxcam on Jetson Tegra and as I know they have not been tested on that platfrom.

**Comment by CPFelix** [comment]
@SokratG Thanks!

**Comment by CPFelix** [comment]
@SokratG Sorry for disturbing you again.Can you provide a short video from four cameras, I want to visualize the final effect.

**Comment by CPFelix** [comment]
@SokratG  And what the function “SVAutoCalib” does？I’m a little confused.

**Comment by SokratG** [comment]
@CPFelix Unfortunately, I don't have access to hardware to capture video from the cameras...
