### ISSUE TITLE
Running on platforms without NVIDIA graphics cards

### ISSUE THREAD

**Issue by SLBiuBiu** [SokratG/Surround-View#17]
Hi:
The platform I am currently using does not have Cuda

- Ubuntu 22.04.2 LTS
- Intel® Core™ i5-10500 CPU @ 3.10GHz × 12
Can it run if I don't have a cuda driver? It’s okay even if the effect is not good.

**Comment by SokratG** [comment]
Hello @SLBiuBiu you cannot run the project without Nvidia GPU
