### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by chenti2x** [SokratG/Surround-View#19]
1.hello,cannot find Real-Time 3D Surround View System for Vehicle Based on Panoramic Stitching Image?why?
2.Is there any other relevant information?

**Comment by SokratG** [comment]
> 1.hello,cannot find Real-Time 3D Surround View System for Vehicle Based on Panoramic Stitching Image?why? 2.Is there any other relevant information?

Hello.
1. https://link.springer.com/chapter/10.1007/978-3-031-11058-0_9 . To search for scientific papers, it is better to use google scholar.
2. No. Only code.
