### ISSUE TITLE
the camera is not fisheye camera?

### ISSUE THREAD

**Issue by fanDongHust** [SokratG/Surround-View#4]
does it support fisheye camera?

how to get the intrinsic and extrinsic camera parameter?

**Comment by fanDongHust** [comment]
question 2 you have answered. thank you!
Could you tell me the procedure to generate new camera calibration files ?

So, the project has two directories with calibration data.
First it's just calibration intrinsic parameters of cameras - focal length, optical centers and distortions -> they are stored in calibrationData directory. You do procedure calibration with some tools like [OpenCV calib](https://docs.opencv.org/3.4/dc/dbb/tutorial_py_calibration.html) or [Matlab calibration toolbox](https://www.mathworks.com/help/vision/camera-calibration.html). Some notes about calibration: for different image resolution you will have different parameters that's important. Ok, You calibrate cameras and save them into files.

Then calibrate the extrinsic parameters. These extrinsic parameters relate to the rotation and translation of the cameras with each others. To calculate the parameters, I used the feature matching and bundle adjustment methods. You can find them in SVAutoCalib module. This module have full extrinsic calibration process and saved into files. Files you can find into "camparamters" directory. The files also have another intrinsic parameters, because parameters must recalibrated after distortion correction. These all can be done in SVAutoCalib module. Also method "init" in SVStitcher class can complete full setup process(see code) just pass your data from cameras.
One more important note - I have 4 cameras, but I divide last camera image into two. Because good calibration of last with first camera images is pretty hard and the easy way to avoid this and just divide one image into two and align them later :)

P.S.
Some notes: If you will use SVAutoCalib module the extrinsic calibration may take some times, because that's depends of feature matching process and therefore your overlapping region of the cameras. In the project I used ORB feature detection, but I don't recommend this algorithm, cause many outliers will be generated. Use better SIFT or BRISK. ORB is good if you wanna use autocalibration cameras on runtime when you want refine camera parameters.
Also, you can use Homography matrix computation cameras with each other. And just mutliply them for get parameters, this must work, I guess. But bundle adjustment everything is needed for get good quality stitching images, because other methods give a rough parameters computation.
So, I hope that's help you)

**Comment by fanDongHust** [comment]
does it support video or picture input? 
fisheye camera captured.

**Comment by SokratG** [comment]
> does it support video or picture input? fisheye camera captured.

Hi!
If you mean support for a video stream from a file, than the answer is "No". About high distortion camera(fisheye), the calibration of this type of lens may differ from that found in the python scripts in the project, for this case see pls [there](https://docs.opencv.org/4.5.5/db/d58/group__calib3d__fisheye.html)
