### ISSUE TITLE
libxcam recommendation?

### ISSUE THREAD

**Issue by jwdinius** [SokratG/Surround-View#7]
Hello,

In this project's README, you state that you recommend Intel's `libxcam` library for production surround view applications?  I was wondering if you have seen a tutorial or a reference implementation using this API that you could share.  I have not had any luck so far with finding good documentation for this library.  Thanks!

**Comment by SokratG** [comment]
> Hello,
> 
> In this project's README, you state that you recommend Intel's `libxcam` library for production surround view applications? I was wondering if you have seen a tutorial or a reference implementation using this API that you could share. I have not had any luck so far with finding good documentation for this library. Thanks!

Hi!
They don't have tutorial or API reference or good documentation. But they have good examples in test folder. For surround view -> [here](https://github.com/intel/libxcam/blob/master/tests/test-surround-view.cpp). After reviewing these examples, I am sure you will immediately understand how to use this library. Also some explanation you can find in issues of the libxcam project.

**Comment by jwdinius** [comment]
Thanks much @SokratG for the suggestions.  I will look into the link provided.
