### ISSUE TITLE
where could i buy the hardware you used?

### ISSUE THREAD

**Issue by fanDongHust** [SokratG/Surround-View#8]
i want to buy the hardware you used,
at least the cameras.
could you give me the link for online purchases?
thank you.

**Comment by SokratG** [comment]
> i want to buy the hardware you used, at least the cameras. could you give me the link for online purchases? thank you.

Hi! So I used this devices - [link](https://www.e-consystems.com/multiple-csi-cameras-for-nvidia-jetson-tx2.asp). Also I recommend to look - SV from NXP [link](https://www.nxp.com/design/designs/i-mx-surround-view-system:SURROUND-VIEW-APPLICATION) they have source code with hardware and good documentation.
